import NavBar from "@/components/NavBar";
import { Inter, Wendy_One } from "next/font/google";
// import "./globals.css";

const inter = Wendy_One({ subsets: ["latin"], weight: "400" });
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Erick Segura",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
